# Generated by Django 5.1.7 on 2025-04-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruitment.job')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruitment.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruitment.candidate')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruitment.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruitment.trainer')),
            ],
        ),
    ]
