# Generated by Django 5.1.7 on 2025-04-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Individual',
            new_name='Person',
        ),
    ]
