# Generated by Django 5.1.7 on 2025-04-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0003_trainer_alter_person_name_alter_person_surname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Candidate',
        ),
    ]
