# Generated by Django 5.1.7 on 2025-04-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0004_rename_person_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='dob',
        ),
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(default='email', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default='12345', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(default='skills', max_length=200),
            preserve_default=False,
        ),
    ]
