# Generated by Django 5.1.7 on 2025-04-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0005_remove_candidate_dob_candidate_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.CharField(default='email', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default='phone', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='qualifications',
            field=models.CharField(default='qualifications', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recruitment.company')),
            ],
        ),
    ]
