# Generated by Django 5.1.7 on 2025-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0006_company_trainer_address_trainer_email_trainer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(default='password', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(default='username', max_length=200),
            preserve_default=False,
        ),
    ]
